=== Alkeari/CulturedStartReloaded-PUBLIC/_Module/SubModule.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Module" type="ModuleType"/>

  <xs:complexType name="IdType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="NameType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="VersionType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="DefaultModuleType">
    <xs:attribute type="xs:boolean" name="value" use="required"/>
  </xs:complexType>
  <xs:simpleType name="ModuleCategoryValueType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Singleplayer" />
      <xs:enumeration value="Multiplayer" />
      <xs:enumeration value="Server" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ModuleCategoryType">
    <xs:attribute type="ModuleCategoryValueType" name="value" use="required"/>
  </xs:complexType>
  <xs:simpleType name="ModuleTypeValueType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Official" />
      <xs:enumeration value="OfficialOptional" />
      <xs:enumeration value="Community" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ModuleTypeType">
    <xs:attribute type="ModuleTypeValueType" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="UrlType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:simpleType name="UpdateInfoValueType">
    <xs:restriction base="xs:string">
      <xs:pattern value="NexusMods:[0-9]+" />
      <xs:pattern value="GitHub:[a-zA-Z0-9.\-_]+/[a-zA-Z0-9.\-_]+" />
      <xs:pattern value="NexusMods:[0-9]+;GitHub:[a-zA-Z0-9.\-_]+/[a-zA-Z0-9.\-_]+" />
      <xs:pattern value="GitHub:[a-zA-Z0-9.\-_]+/[a-zA-Z0-9.\-_]+;NexusMods:[0-9]+" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="UpdateInfoType">
    <xs:attribute type="UpdateInfoValueType" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="DependedModuleType">
    <xs:attribute type="xs:string" name="Id" use="required"/>
    <xs:attribute type="xs:string" name="DependentVersion" use="optional"/>
    <xs:attribute type="xs:boolean" name="Optional" use="optional"/>
  </xs:complexType>
  <xs:complexType name="ModuleWithIdType">
    <xs:attribute type="xs:string" name="Id" use="required"/>
  </xs:complexType>
  <xs:complexType name="DependedModulesType">
    <xs:sequence>
      <xs:element type="DependedModuleType" name="DependedModule" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ModulesToLoadAfterThisType">
    <xs:sequence>
      <xs:element type="ModuleWithIdType" name="Module" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="IncompatibleModulesType">
    <xs:sequence>
      <xs:element type="ModuleWithIdType" name="Module" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="DependedModuleMetadataOrderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LoadBeforeThis" />
      <xs:enumeration value="LoadAfterThis" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="DependedModuleMetadataType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="DependedModuleMetadataOrderType" name="order" use="required"/>
    <xs:attribute type="xs:string" name="version" use="optional"/>
    <xs:attribute type="xs:string" name="optional" use="optional"/>
    <xs:attribute type="xs:string" name="incompatible" use="optional"/>
  </xs:complexType>
  <xs:complexType name="DependedModuleMetadatasType">
    <xs:sequence>
      <xs:element type="DependedModuleMetadataType" name="DependedModuleMetadata" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DLLNameType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="SubModuleClassTypeType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="AssemblyType">
    <xs:attribute type="xs:string" name="value"/>
  </xs:complexType>
  <xs:complexType name="AssembliesType">
    <xs:sequence>
      <xs:element type="AssemblyType" name="Assembly" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="TagType">
    <xs:attribute type="xs:string" name="key"/>
    <xs:attribute type="xs:string" name="value"/>
  </xs:complexType>
  <xs:complexType name="TagsType">
    <xs:sequence>
      <xs:element type="TagType" name="Tag" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SubModuleType">
    <xs:sequence>
      <xs:element type="NameType" name="Name"/>
      <xs:element type="DLLNameType" name="DLLName"/>
      <xs:element type="SubModuleClassTypeType" name="SubModuleClassType"/>
      <xs:element type="AssembliesType" name="Assemblies"/>
      <xs:element type="TagsType" name="Tags"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="SubModulesType">
    <xs:sequence>
      <xs:element type="SubModuleType" name="SubModule" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XmlNameType">
    <xs:attribute type="xs:string" name="id" use="required"/>
    <xs:attribute type="xs:string" name="path" use="required"/>
  </xs:complexType>
  <xs:complexType name="GameTypeType">
    <xs:attribute type="xs:string" name="value" use="required"/>
  </xs:complexType>
  <xs:complexType name="IncludedGameTypesType">
    <xs:sequence>
      <xs:element type="GameTypeType" name="GameType" maxOccurs="unbounded" minOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XmlNodeType">
    <xs:sequence>
      <xs:element type="XmlNameType" name="XmlName"/>
      <xs:element type="IncludedGameTypesType" name="IncludedGameTypes"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="XmlsType">
    <xs:sequence>
      <xs:element type="XmlNodeType" name="XmlNode" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ISKLType">
    <xs:sequence>
      <xs:element type="IdType" name="NexusId" minOccurs="0" maxOccurs="1"/>
      <xs:element type="UrlType" name="Url" minOccurs="0" maxOccurs="1"/>
      <xs:element type="IdType" name="Author" minOccurs="0" maxOccurs="1"/>
      <xs:element type="IdType" name="Description" minOccurs="0" maxOccurs="1"/>
      <xs:element type="IdType" name="Category" minOccurs="0" maxOccurs="1"/>
      <xs:element type="UrlType" name="IconUrl" minOccurs="0" maxOccurs="1"/>
      <xs:element type="UrlType" name="ChangelogUrl" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="ModuleType">
    <xs:sequence>
      <xs:element type="IdType" name="Id" minOccurs="1" maxOccurs="1"/>
      <xs:element type="NameType" name="Name" minOccurs="1" maxOccurs="1"/>
      <xs:element type="VersionType" name="Version" minOccurs="1" maxOccurs="1"/>
      <xs:element type="DefaultModuleType" name="DefaultModule" minOccurs="0" maxOccurs="1"/>
      <xs:element type="ModuleCategoryType" name="ModuleCategory" minOccurs="0" maxOccurs="1"/>
      <xs:element type="ModuleTypeType" name="ModuleType" minOccurs="0" maxOccurs="1"/>
      <xs:element type="UrlType" name="Url" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Community extension.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="UpdateInfoType" name="UpdateInfo" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Community extension. Should either be 'NexusMods:%MODID%' or 'GitHub:%USER%/%REPO%'
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="DependedModulesType" name="DependedModules" minOccurs="0" maxOccurs="1"/>
      <xs:element type="ModulesToLoadAfterThisType" name="ModulesToLoadAfterThis" minOccurs="0" maxOccurs="1"/>
      <xs:element type="IncompatibleModulesType" name="IncompatibleModules" minOccurs="0" maxOccurs="1"/>
      <xs:element type="DependedModuleMetadatasType" name="DependedModuleMetadatas" minOccurs="0" maxOccurs="1">
        <xs:annotation>
          <xs:documentation>
            Community extension.
          </xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element type="SubModulesType" name="SubModules" minOccurs="0" maxOccurs="1"/>
      <xs:element type="XmlsType" name="Xmls" minOccurs="0" maxOccurs="1"/>
      <xs:element type="ISKLType" name="ISKL" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Alkeari/CulturedStartReloaded-PUBLIC/_Module/SubModule.xml
<?xml version="1.0" encoding="UTF-8"?>
<Module xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:noNamespaceSchemaLocation="SubModule.xsd" >
  <Id value="$moduleid$" />
  <Name value="$modulename$" />
  <Version value="v$version$" />
  <DefaultModule value="false" />
  <ModuleCategory value="Singleplayer"/>
  <ModuleType value="Community" />
  <Url value="$moduleurl$" />
  <DependedModules>
    <DependedModule Id="Bannerlord.Harmony" DependentVersion="v$harmonyversion$" />
    <DependedModule Id="Bannerlord.ButterLib" DependentVersion="v$butterlibversion$" />
    <DependedModule Id="Bannerlord.MBOptionScreen" DependentVersion="v$mcmversion$" />
    <DependedModule Id="Native" DependentVersion="$gameversion$" />
    <DependedModule Id="SandBoxCore" DependentVersion="$gameversion$" />
    <DependedModule Id="Sandbox" DependentVersion="$gameversion$" />
    <DependedModule Id="StoryMode" DependentVersion="$gameversion$" />
  </DependedModules>
  <!-- Community Dependency Metadata -->
  <!-- https://github.com/BUTR/Bannerlord.BLSE#community-dependency-metadata -->
  <DependedModuleMetadatas>
    <DependedModuleMetadata id="Bannerlord.Harmony" order="LoadBeforeThis" version="v$harmonyversion$" />
    <DependedModuleMetadata id="Bannerlord.ButterLib" order="LoadBeforeThis" version="v$butterlibversion$" />
    <DependedModuleMetadata id="Bannerlord.MBOptionScreen" order="LoadBeforeThis" version="v$mcmversion$" />
    <DependedModuleMetadata id="Native" order="LoadBeforeThis" version="$gameversion$.*" />
    <DependedModuleMetadata id="SandBoxCore" order="LoadBeforeThis" version="$gameversion$.*" />
    <DependedModuleMetadata id="Sandbox" order="LoadBeforeThis" version="$gameversion$.*" />
    <DependedModuleMetadata id="StoryMode" order="LoadBeforeThis" version="$gameversion$.*" />
  </DependedModuleMetadatas>
  <SubModules>
    <!-- Bannerlord Module Loader. Do not change the name! -->
    <SubModule>
      <Name value="Bannerlord Module Loader" />
      <DLLName value="Bannerlord.ModuleLoader.$moduleid$.dll" />
      <SubModuleClassType value="Bannerlord.ModuleLoader.$moduleid$" />
      <Assemblies/>
      <Tags>
        <Tag key="LoaderFilter" value ="$moduleid$.*.dll" />
      </Tags>
    </SubModule>
  </SubModules>
</Module>
